name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true 
  assets:
    - assets/logo.png
    - assets/pizza_margherita.png
    - assets/pizza_pepperoni.png
    - assets/pizza_quatro_queijos.png
    - assets/pizza_frango_catupiry.png
    - assets/pizza_portuguesa.png
    - assets/pizza_calabresa.png
    - assets/pizza_chocolate.png 
    - assets/pizza_banana.png 
    - assets/pizza_doce_leite.png 
    - assets/coca.png 
    - assets/suco_laranja.png 
    - assets/agua.png 
    - assets/caipirinha.png 
    - assets/negroni.png
    - assets/pina_colada.png

