// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBQIxe4h7eN6-8KkhE52gKZDggk51Idg',
    appId: '1:41102898805:android:fa6b2db32b9dee53662a3c',
    messagingSenderId: '41102898805',
    projectId: 'pizzaria-df5bb',
    storageBucket: 'pizzaria-df5bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVrzBL4_Ow5u2LZqaCAUQksxrWa-4STU',
    appId: '1:41102898805:ios:98e89dbea183df7e662a3c',
    messagingSenderId: '41102898805',
    projectId: 'pizzaria-df5bb',
    storageBucket: 'pizzaria-df5bb.firebasestorage.app',
    iosBundleId: 'com.example.pizzariaflutterdf5bb',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxa8sXahuBnv5K0Hn3RuXlGEZrD-MOMSA',
    appId: '1:41102898805:web:1d77a2da7db9df41662a3c',
    messagingSenderId: '41102898805',
    projectId: 'pizzaria-df5bb',
    authDomain: 'pizzaria-df5bb.firebaseapp.com',
    storageBucket: 'pizzaria-df5bb.firebasestorage.app',
  );

}